### ISSUE TITLE
docker-compose 失敗

### ISSUE THREAD

**Issue by changchichung** [mylxsw/wizard#203]
git clone 下來之後，參照之前的issue ，下載了 https://github.com/mylxsw/wizard/releases/download/1.2.0/vendor.zip 並解壓到根目錄
接著我只改了 docker-compose.yml 裡面的 port
然後直接 up
開啟URL 就會發生錯誤
```

Fatal error: Uncaught Error: Call to undefined function Symfony\Component\HttpFoundation\str_starts_with() in /webroot/wizard/vendor/symfony/http-foundation/ServerBag.php:32 Stack trace: #0 /webroot/wizard/vendor/symfony/http-foundation/Request.php(271): Symfony\Component\HttpFoundation\ServerBag->getHeaders() #1 /webroot/wizard/vendor/symfony/http-foundation/Request.php(247): Symfony\Component\HttpFoundation\Request->initialize(Array, Array, Array, Array, Array, Array, NULL) #2 /webroot/wizard/vendor/symfony/http-foundation/Request.php(1977): Symfony\Component\HttpFoundation\Request->__construct(Array, Array, Array, Array, Array, Array, NULL) #3 /webroot/wizard/vendor/symfony/http-foundation/Request.php(293): Symfony\Component\HttpFoundation\Request::createRequestFromFactory(Array, Array, Array, Array, Array, Array) #4 /webroot/wizard/vendor/laravel/framework/src/Illuminate/Http/Request.php(59): Symfony\Component\HttpFoundation\Request::createFromGlobals() #5 /webroot/wizard/public/index.php(53): Illuminate\Http\Request: in /webroot/wizard/vendor/symfony/http-foundation/ServerBag.php on line 32
```
docker-compose logs -f 的訊息如下
```
php_1      | Warning: Class 'Tightenco\Collect\Support\LazyCollection' not found in /webroot/wizard/vendor/tightenco/collect/src/Collect/Support/alias.php on line 22
php_1      | 
php_1      | Parse error: syntax error, unexpected ')' in /webroot/wizard/vendor/tightenco/collect/src/Collect/Support/Traits/EnumeratesValues.php on line 739
php_1      | 
php_1      | Warning: Class 'Tightenco\Collect\Support\LazyCollection' not found in /webroot/wizard/vendor/tightenco/collect/src/Collect/Support/alias.php on line 22
php_1      | 
php_1      | Parse error: syntax error, unexpected ')' in /webroot/wizard/vendor/tightenco/collect/src/Collect/Support/Traits/EnumeratesValues.php on line 739
wizard_php_1 exited with code 255

```
請問該如何處理？

**Comment by changchichung** [comment]
自己回覆一下

後來依照這篇
https://github.com/mylxsw/wizard/wiki/Docker-compose-up-%E5%90%AF%E5%8A%A8%E5%A4%B1%E8%B4%A5%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88

改下載最新版 (1.2.7) 的 vendor.zip  覆蓋過去就可以了
