### ISSUE TITLE
升级之后比较差异500错误

### ISSUE THREAD

**Issue by EchoYao** [mylxsw/wizard#56]
[2020-01-05 16:07:59] production.ERROR: Class 'SebastianBergmann\Diff\Output\UnifiedDiffOutputBuilder' not found {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'SebastianBergmann\\Diff\\Output\\UnifiedDiffOutputBuilder' not found at /data/webroot/docapi/app/Http/Controllers/CompareController.php:59)
[stacktrace]
#0 [internal function]: App\\Http\\Controllers\\CompareController->compare(Object(Illuminate\\Http\\Request))
#1 /data/webroot/docapi/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#2 /data/webroot/docapi/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('compare', Array)
#3 /data/webroot/docapi/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\CompareController), 'compare')

**Comment by mylxsw** [comment]
需要更新依赖，使用composer install或者直接下载最新release下的vendor.zip文件覆盖项目下的vendor文件夹

**Comment by EchoYao** [comment]
> 需要更新依赖，使用composer install或者直接下载最新发布下一个的vendor.zip文件覆盖项目下的供应商文件夹

我的PHP版本7.3 使用composer install 报错。覆盖vendor 基本解决。
